version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al puerto 3000 del host
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - ./videos:/app/videos # Monta la carpeta de videos
      - ./youtube-links.json:/app/youtube-links.json # Monta el archivo de enlaces de YouTube
    command: npm start
